docs(Accounts): More Details In Accounting Period
frappe/erpnext_documentation pull request #145
Opened 2020-09-08 14:06 UTC by abhishekbalam

Added points:
- Why accounting period is needed?
- What is the "Closed" option for the selected transactions used for?

Also changed intro.

2020-09-17 15:45 UTC, akshitakl requested changes

2020-09-17 15:45 UTC, akshitakl commented on erpnext_documentation/www/docs/user/manual/en/accounts/accounting-period.md
> +## 2. What is the "Closed" option for the selected transactions used for?
Please add an image in this section.

2020-09-18 13:12 UTC, abhishekbalam commented on erpnext_documentation/www/docs/user/manual/en/accounts/accounting-period.md
> +## 2. What is the "Closed" option for the selected transactions used for?
Added 👍

2020-09-21 10:20 UTC, prasadarr requested changes

2020-09-21 10:20 UTC, prasadarr commented on erpnext_documentation/www/docs/user/manual/en/accounts/accounting-period.md
> +In ERPNext, Accounting Period is a timeframe outside which selected submittable transactions (like Sales/Purchase Invoice, Stock Entry, Payroll Entry, Journal Entry etc) are not allowed to be created
```suggestion
In ERPNext, Accounting Period is a timeframe outside which selected submittable transactions (like Sales/Purchase Invoice, Stock Entry, Payroll Entry, Journal Entry etc) are not allowed to be created. In other words, the selected transactions are only allowed to be created within the defined Accounting Period.
```

2020-09-21 10:20 UTC, prasadarr commented on erpnext_documentation/www/docs/user/manual/en/accounts/accounting-period.md
> +When transactions are submitted they affect the ledgers and hence the reports which process the ledger data.
```suggestion
When transactions are submitted, they affect the ledgers and the reports which process the ledger data.
```

2020-09-21 10:20 UTC, prasadarr commented on erpnext_documentation/www/docs/user/manual/en/accounts/accounting-period.md
> +The "Closed" option in the childtable for transaction doctypes is to select which of them are to be restricted after the end of the Accounting Period.
```suggestion
The "Closed" option in the childtable for transaction doctypes is used to select which of them are to be restricted after the end of the Accounting Period.
```

2020-09-21 10:20 UTC, prasadarr commented on erpnext_documentation/www/docs/user/manual/en/accounts/accounting-period.md
> +Do note that if the Accounting Period ends and if any of the selected transactions in the child table don't have "Closed" checked, then they won't be restricted after the accounting period ends.
```suggestion
Do note that if the Accounting Period ends and if any of the selected transactions in the child table don't have "Closed" checked, then they won't be restricted after the Accounting Period ends.
```

2020-09-21 13:28 UTC, akshitakl approved these changes

2020-09-21 13:28 UTC, merged