docs: Event streaming fixes
frappe/erpnext_documentation pull request #146
Opened 2020-09-09 06:40 UTC by ruchamahabal

docs for recent changes in https://github.com/frappe/frappe/pull/11458

2020-09-09 06:44 UTC, ruchamahabal commented
Spell check failing due to `eval`

2020-10-07 12:13 UTC, michellealva requested changes

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
> +2. Open the user document you are going to use as an event subscriber. Scroll down to the section labelled "API access". In that section, generate keys for the user by clicking on **Generate Keys** b
"API Access"

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
> +### 2.2 Generate Keys for the Event Subscriber on the consumer site
Consumer Site

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
> +### 2.3 Create an Event Producer on the consumer site
Event Producer on the Consumer Site

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
> +3. Enter the site URL of the site you want to subscribe to (in this case http://test_site_producer:8000), in the Producer URL field.
Enter the URL of the site you want to subscribe to

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
> +4. Add all the Document Types you want to subscribe to, in the Event Producer Document Types child table.
child table.. remove child?

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
>  5. If you want to have the created documents with the same name as it is on the remote Event Producer site, check the 'Use Same Name' checkbox in the child table against the required Document Type.
again.. remove child? Just keep table

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
> +6. Set the Event Subscriber field to the user that will be used to create the documents fetched from the Event Producer. You need to create the same user both ways, i.e on the Event Consumer as well
i.e.

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
> +7. Paste the API key and secret you generated in the first step (2.1) in the API key and API secret fields respectively.
API Key and API Secret

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
> +>**Note**: If at all the API Secret is changed for the users on any of these sites, you will have to manually update the keys in Event Producer as well as the Event Consumer on both the sites.
update the keys in the Event Producer

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
> +1. After the Event Producer has been created, an Event Consumer automatically gets created on the producer site. By default all the Subscribed Document Types have the status as 'Pending'. In order to
By default, all the Subscribed ...

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
> +As an event consumer, if you wish to unsubscribe from the updates for any doctypes you had previously subscribed to, check unsubscribe against the doctype. You will not receive any more updates from
Event Consumer

2020-10-07 12:13 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/automation/event_streaming.md
>  Event Update Log logs every create, update, and delete for documents that have consumers on the Event Producer site.
"Event Update Log" logs every create, update, and delete action for documents that have consumers on the Event Producer site.

2020-10-13 12:05 UTC, michellealva approved these changes

2020-10-13 12:19 UTC, merged