docs: correct spellings
frappe/erpnext_documentation pull request #157
Opened 2020-09-28 06:06 UTC by hasnain2808

2020-10-07 10:54 UTC, michellealva requested changes

2020-10-07 10:54 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/regional/united_arab_emirates/uae-vat-setup.md
> +Set tax registration number in the field tax id for the customer, supplier and company
Set Tax Registration Number in the field, Tax ID for the Customer, Supplier, and Company

2020-10-07 10:54 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/regional/united_arab_emirates/uae-vat-setup.md
> +ERPNext provides 2 default print format
ERPNext provides two default print formats

2020-10-08 05:02 UTC, prasadarr approved these changes

2020-10-08 05:02 UTC, merged