docs: opening invoice creation tool
frappe/erpnext_documentation pull request #181
Opened 2020-10-22 16:10 UTC by nextchamp-saqib

ref: https://github.com/frappe/erpnext/pull/23595

2020-10-23 11:55 UTC, michellealva requested changes

2020-10-23 11:55 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/accounts/opening-invoice-creation-tool.md
> +The Opening Invoice Creation Tool allows importing data of outstanding purchase or sales invoices into ERPNext. This specific tool is used in place of Data Import Tool for cases where item data is ir
```suggestion
The Opening Invoice Creation Tool allows importing data of outstanding Purchase or Sales Invoices into ERPNext. This specific tool is used in place of the Data Import Tool for cases where the Item data is irrelevant and outstanding balances against Customers/Suppliers are to be imported into ERPNext.
```

2020-10-23 11:55 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/accounts/opening-invoice-creation-tool.md
> +To access the tool, go to:
```suggestion
To access the Opening Invoice Creation Tool, go to:
```

2020-10-23 11:55 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/accounts/opening-invoice-creation-tool.md
> +3. Checking Create Missing Party will automatically create customers or suppliers if missing according to the name provided in Party column.
```suggestion
3. Checking the "Create Missing Party" checkbox will automatically create customers or suppliers if missing according to the name provided in the Party column.
```

2020-10-23 11:55 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/accounts/opening-invoice-creation-tool.md
> +4. Fill up the Invoices table. It consists of following fields:
```suggestion
4. Fill up the Invoices table. It consists of the following fields:
```

2020-10-23 11:55 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/accounts/opening-invoice-creation-tool.md
> +    - **Party**: You can select a customer/supplier or enter name of a new one which will be automatically created.
```suggestion
    - **Party**: You can select an existing Customer/Supplier or enter the name of a new one which will be automatically created.
```

2020-10-23 11:55 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/accounts/opening-invoice-creation-tool.md
> +> **Tip**: You can click the download button to download an excel sheet which you can fill up easily with appropriate data. If you have downloaded the excel sheet, then use the upload button to uploa
```suggestion
> **Tip**: You can click the download button to download an excel sheet that you can fill up easily with appropriate data. If you have downloaded the excel sheet, then use the Upload button to upload it. Once you upload the sheet, the table will be filled with appropriate data rows.
```

2020-10-23 15:26 UTC, nextchamp-saqib commented on erpnext_documentation/www/docs/user/manual/en/accounts/opening-invoice-creation-tool.md
> +> **Tip**: You can click the download button to download an excel sheet which you can fill up easily with appropriate data. If you have downloaded the excel sheet, then use the upload button to uploa
```suggestion
> **Tip**: You can click the download button to download an excel sheet that you can fill up easily with appropriate data. If you have downloaded the excel sheet, then use the Upload button to upload it. Once you upload the sheet, the table will be filled with appropriate data rows.
```

2020-10-26 08:34 UTC, michellealva approved these changes

2020-10-26 08:38 UTC, merged