update: separated payroll from HR and added content for multi-currency
frappe/erpnext_documentation pull request #220
Opened 2020-12-11 11:29 UTC by AfshanKhan

For reference of multi-currency changes view https://github.com/frappe/erpnext/pull/23519

2020-12-23 12:02 UTC, prasadarr requested changes

2020-12-23 12:02 UTC, prasadarr commented on erpnext_documentation/www/docs/user/manual/en/payroll/payroll-entry.md
> +> **Note:** Only Salary Slips in Draft mode will be considered while making the Journal Entry to record salary accrual. For each Submitted Salary Slips Journal Entry has to be made manually.
```suggestion
> **Note:** Only Salary Slips in Draft mode will be considered while making the Journal Entry to record salary accrual. For each Submitted Salary Slip, Journal Entry has to be made manually.
```

2020-12-23 12:02 UTC, prasadarr commented on erpnext_documentation/www/docs/user/manual/en/payroll/payroll-reports.md
> +## 2.Salary Payments Based On Payment Mode
```suggestion
## 2. Salary Payments Based On Payment Mode
```
add space after dot in all following headings

2020-12-23 12:05 UTC, prasadarr requested changes

2020-12-23 12:05 UTC, prasadarr commented on erpnext_documentation/www/docs/user/manual/en/payroll/salary-structure.md
> +3. Select the Company Name, Payroll Frequency and *Currency(Added in version 13)*.
```suggestion
3. Select the Company Name, Payroll Frequency and *Currency(Added in version 13)*. You can pay salary in different currencies, i.e. multi-currency payroll.
```

2021-04-07 05:35 UTC, AfshanKhan commented on erpnext_documentation/www/docs/user/manual/en/human-resources/human-resources-reports.md
> +<img alt="Employee Leave Balance" class="screenshot" src="{{docs_base_url}}/assets/img/human-resources/monthly-attendance-sheet-report.png">
That is because it was already present. I have just added the link here.

2021-04-07 05:35 UTC, AfshanKhan commented on erpnext_documentation/www/docs/user/manual/en/payroll/employee-exemption-categories-and-sub-categories.md
> + <img class="screenshot" alt="Employee Tax Exemption Category" src="{{docs_base_url}}/assets/img/payroll/employee-tax-exemption-sub-category1.png">
That is because it was already present. I have just added the link here.

2021-04-07 05:35 UTC, AfshanKhan commented on erpnext_documentation/www/docs/user/manual/en/payroll/employee-exemption-categories-and-sub-categories.md
> + <img class="screenshot" alt="Employee Tax Exemption Category" src="{{docs_base_url}}/assets/img/payroll/employee-tax-exemption-category1.png">
That is because it was already present. I have just added the link here.

2021-04-19 12:37 UTC, barredterra commented
@AfshanKhan please fix the spelling mistakes. Unknown words such as "IFSC" can be added to [cspell_ignored_words.txt](https://github.com/frappe/erpnext_documentation/blob/master/spell_checker/cspell_ignored_words.txt).

2021-04-19 14:35 UTC, AfshanKhan commented
> @AfshanKhan please fix the spelling mistakes. Unknown words such as "IFSC" can be added to [cspell_ignored_words.txt](https://github.com/frappe/erpnext_documentation/blob/master/spell_checker/cspell_ignored_words.txt).

Done

2021-04-19 14:59 UTC, barredterra commented on spell_checker/cspell_ignored_words.txt
> +ESOPS
```suggestion
SINV
RFID
Unpledge
Unsubmitted
IFSC
MICR
ESOPS
```

Wrong words shouldn't be included here. For example, "updation" is not correct english.

2021-06-21 17:37 UTC, barredterra commented
@AfshanKhan docs have been refactored to have a v12 and v13 folder for the respective version of ERPNext. Kindly update your PR to take this new structure into account.

2021-06-22 07:29 UTC, closed without merging

2021-07-14 07:57 UTC, Anurag810 commented
@AfshanKhan please move these documents according to Version