docs: Hide Descendants on User Permissions
frappe/erpnext_documentation pull request #238
Opened 2021-01-22 06:31 UTC by marination

Docs for https://github.com/frappe/frappe/pull/12209
 Segregated **Advanced Control** section
![screencapture-develop-in-8004-docs-user-manual-en-setting-up-users-and-permissions-user-permissions-2021-01-22-12_03_08](https://user-images.githubusercontent.com/25857446/105455428-79f10880-5ca9-11eb-8e5c-d208091ba545.png)

2021-01-22 06:49 UTC, marination commented
spellcheck fails on the work 'Unico' 🤷🏻

2021-01-28 04:42 UTC, michellealva requested changes

2021-01-28 04:42 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/setting-up/users-and-permissions/user-permissions.md
> +4. If you check 'Is Default', the value selected in 'For Value' will be used by default for any future transactions by this user. That is, if company 'Unico Plastics Inc.' is selected as 'For Value',
```suggestion
4. If you check 'Is Default', the value selected in 'For Value' will be used by default for any future transactions by this user. That is if company 'Unico Plastics Inc.' is selected as 'For Value', this Company will be set as default for all future transactions by this user.
```

2021-01-28 04:42 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/setting-up/users-and-permissions/user-permissions.md
> +In Advanced control, you can have better command over where the User Permission is applied.
```suggestion
In Advanced Control, you can have better command over where the User Permission is applied.
```

2021-01-28 04:42 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/setting-up/users-and-permissions/user-permissions.md
>  ### 2.1 Advanced control
```suggestion
### 2.1 Advanced Control
```

2021-01-28 04:42 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/setting-up/users-and-permissions/user-permissions.md
> +Let's assume **For Value**, 'Unico Plastics Inc.', has a child company 'Unico Toys'. When a User Permission is created for 'Unico Plastics Inc.', permissions for it's descendants are granted as well.
```suggestion
Let's assume **For Value**, 'Unico Plastics Inc.', has a child company 'Unico Toys'. When a User Permission is created for 'Unico Plastics Inc.', permissions for its descendants are granted as well.
```

2021-01-28 04:42 UTC, michellealva commented on erpnext_documentation/www/docs/user/manual/en/setting-up/users-and-permissions/user-permissions.md
> +For example, User Bruce is restricted to Company 'Unico Plastics Inc.'
```suggestion
For example, the user, Bruce is restricted to Company 'Unico Plastics Inc.'
```

2021-02-08 06:17 UTC, michellealva approved these changes

2021-02-08 06:17 UTC, merged