fix: unintentional code block rendering
frappe/erpnext_documentation pull request #324
Opened 2021-05-13 10:22 UTC by ankush

Problem: ![image](https://user-images.githubusercontent.com/9079960/118112627-e29ff480-b402-11eb-92ab-32507d4f4da1.png)

4 spaces => start of code block in markdown. As either of the option is okay in the following case they can be on a single line instead.

2021-06-21 17:42 UTC, barredterra commented
@ankush docs have been refactored to have a v12 and v13 folder for the respective version of ERPNext. Kindly update your PR to take this new structure into account.

2021-06-25 02:16 UTC, asbasawaraj requested changes
Please update PR as per version-specific documentation.

2021-06-25 05:55 UTC, ankush commented
@asbasawaraj done

2021-06-25 10:57 UTC, barredterra approved these changes

2021-06-25 10:58 UTC, merged